TRUNCATE TABLE users, reviews, favourites RESTART IDENTITY;

INSERT INTO users (email, password, name) VALUES ('josh@makers.com', 'password!123', 'Josh');
INSERT INTO users (email, password, name) VALUES ('ella@makers.com', 'password!123', 'Ella');
INSERT INTO users (email, password, name) VALUES ('maria@makers.com', 'password!123', 'Maria');
INSERT INTO users (email, password, name) VALUES ('kevwe@makers.com', 'password!123', 'Kevwe');
INSERT INTO reviews (place_id, comment, rating, date_posted, user_id, user_name) VALUES ('ChIJ6ewepxYCdkgRnZylbn6CgkI', 'Delicious vegan brunch in this pretty cafe! We went there on Saturday, it was quite busy, but worth it to stay and try the vegan food! Good filling amount, perfectly nutritional and tasteful, and the salted caramel coffee is Top too! Just the prices are higher, so I would not go every week or two. Otherwise, highly recommended to try them out! :)', 4, '2022-01-01', 1, 'Josh');
INSERT INTO reviews (place_id, comment, rating, date_posted, user_id, user_name) VALUES ('ChIJ6ewepxYCdkgRnZylbn6CgkI', 'Came here for the first time only recently as I have a usual spot I go to in this area, but I was glad to make the detour and visit a new vegan place. It’s down a little off-road which feels really safe, modern and welcoming. The interior feels warm and genuine and not just a place for Instagram! Food was great, exceptionally tasty and colourful, although it came out lukewarm which was disappointing', 3, '2022-03-01', 2, 'Ella');
INSERT INTO reviews (place_id, comment, rating, date_posted, user_id, user_name) VALUES ('ChIJ6ewepxYCdkgRnZylbn6CgkI', 'Fabulous!!! The staff was so friendly and accommodating! Coffee was great and the space is beautiful and comfortable. Wifi was available and plenty of seating! Will be back for food- thank you!', 5, '2022-05-01', 3, 'Maria');
INSERT INTO reviews (place_id, comment, rating, date_posted, user_id, user_name) VALUES ('ChIJ6ewepxYCdkgRnZylbn6CgkI', 'The entrance of the restaurant can be a bit hidden and google map brought me here eventually. The ambience of the restaurant is amazing. Ordered the milkshake and I think it tasted brilliant with the natural ingredients put in there. I ordered a Malaysian curry - aroma smell really nice and you do get a hearty healthy warm flavours into your body. Ordered another Bali bowl which is essentially courgette salad with lots of different mixture of healthy ingredients in it. It’s absolutely incredible place for this.', 1, '2022-01-01', 1, 'Kevwe');
INSERT INTO reviews (place_id, comment, rating, date_posted, user_id, user_name) VALUES ('ChIJ7x3Pe11ZwokRLpfe6va9dqs', 'Love this hidden gem of a vibe! Small menu but everything you need on it, comfy settings with a Bali/Ibiza vibe to it in the sunshine. Staff were efficient yet relaxed to suit the surroundings. Met one of owners Sophie she was sound and down to earth. Good luck with the second opening.', 1, '2022-01-01', 1, 'Josh');
INSERT INTO reviews (place_id, comment, rating, date_posted, user_id, user_name) VALUES ('ChIJ7x3Pe11ZwokRLpfe6va9dqs', 'The food is delicious but the service in the restaurant is amusing. We booked a table over the phone for 10am on a Saturday. When we got there the place was shut. We had to knock on the shutters to be let in. Only one guy was working which meant we had to wait over an hour. It might be quicker to fly to Dhaka for breakfast next time', 1, '2022-01-01', 1, 'Kevwe');
INSERT INTO reviews (place_id, comment, rating, date_posted, user_id, user_name) VALUES ('ChIJ7x3Pe11ZwokRLpfe6va9dqs', 'Food was great as always, ate in for the first time after ordering from them normally. There really only enough space in the restaurant for a small group, but would still recommend it. The staff are all great and accomodating. Worth noting that its a dry restaurant, but we brought our own, which they were fine with.', 1, '2022-01-01', 1, 'Josh');
INSERT INTO reviews (place_id, comment, rating, date_posted, user_id, user_name) VALUES ('ChIJ7x3Pe11ZwokRLpfe6va9dqs', 'Great diner. Intense flavours, good quality of food. There is not much space inside restaurant 2-3 tables max. We had to wait 45 min for our food because they where really busy at Sunday afternoon. Waiter offered us few samosas on house for that,it was nice on their part. I recommend collection/delivery if you dont want to smell like a kitchen. I will be back to try their other specials.', 1, '2022-01-01', 1, 'Kevwe');
INSERT INTO reviews (place_id, comment, rating, date_posted, user_id, user_name) VALUES ('ChIJ7x3Pe11ZwokRLpfe6va9dqs', 'Food in this café is fresh, tasty and simply delicious. Portions are generous and ingredients clearly quality and fresh.
We came here first about 4 years ago and there was a more extensive menu there and more traditional health vegan food so when yesterday we saw the smaller menu with what looked more liked the current trend for “dirty” fast vegan food I felt disappointed. When the food arrived those thoughts changed fast as there is nothing “fast” food about their sandwiches, salad and chips. I had the chick-pea tuna melt toastie and it was packed full of a delicious mix that was exactly like a tuna melt but not soggy, nor too full of mayo. Perfect texture, balance and seasoning. My husband had the Seitan deli sandwich and was equally delighted. Chips were lovely too.
We visited on a Monday lunchtime and cafe was full. Great atmosphere and a trendy vibe.
We’ll be back.', 1, '2022-01-01', 1, 'Maria');
INSERT INTO reviews (place_id, comment, rating, date_posted, user_id, user_name) VALUES ('ChIJhesNT51ZwokRqIACbMxk2BQ', 'Food in this café is fresh, tasty and simply delicious. Portions are generous and ingredients clearly quality and fresh.
We came here first about 4 years ago and there was a more extensive menu there and more traditional health vegan food so when yesterday we saw the smaller menu with what looked more liked the current trend for “dirty” fast vegan food I felt disappointed. When the food arrived those thoughts changed fast as there is nothing “fast” food about their sandwiches, salad and chips. I had the chick-pea tuna melt toastie and it was packed full of a delicious mix that was exactly like a tuna melt but not soggy, nor too full of mayo. Perfect texture, balance and seasoning. My husband had the Seitan deli sandwich and was equally delighted. Chips were lovely too.
We visited on a Monday lunchtime and cafe was full. Great atmosphere and a trendy vibe.
We’ll be back.', 1, '2022-01-01', 1, 'Ella');
INSERT INTO reviews (place_id, comment, rating, date_posted, user_id, user_name) VALUES ('ChIJhesNT51ZwokRqIACbMxk2BQ', 'I absolutely love this place! I’ve been coming since it was Pogo and I’ve always enjoyed their food and ethic. The place is full of the diversity of New York, reasonably priced as the portions are large! Staff are super friendly. Get down early for an epic Sunday breakfast, you won’t be disappointed!', 1, '2022-01-01', 1, 'Josh');
INSERT INTO reviews (place_id, comment, rating, date_posted, user_id, user_name) VALUES ('ChIJhesNT51ZwokRqIACbMxk2BQ', 'Fantastic place with comfortable wooden seating benches, pillows along the windows seating, eclectic posters and decor and buzzy but not overtly loud or obnoxious convo happening. Although £12 for my lentil burger made me blanche, the generous sides of salad and housemade slaw (I asked for no fries nor burger bun) made it all worth it. There’s so much on the plate I boxed half for home (I had drank a smoothie before I had arrived here). The slaw in particular is divine: it doesn’t have that gross mayo gloppiness I usually despise. It’s quite fresh. There’s a lovely vinaigrette on the greens and the burger has a moreish artichoke sauce. The staff is friendly as are the customers; dog-friendly too!', 1, '2022-01-01', 1, 'Maria');
INSERT INTO favourites (place_id, user_id, name) VALUES ('ChIJk2NryLQpQg0R6SZUS4VF-84', 1, 'THUNDER Vegan Malasaña');
INSERT INTO favourites (place_id, user_id, name) VALUES ('ChIJr7qXjTYCdkgRu5uGS3VCckg', 2, 'Lovegift Vegan');